// 
// Generated by oce-gen
// DO NOT EDIT
// 
use serde::Deserialize;

#[derive(Deserialize, Default)]
#[serde(default)]
pub struct BorrowRate {
    // no description
    // example value: BTC
    #[serde(rename = "coin")]
    pub r#coin: String,
    
    // estimated hourly borrow rate for the next spot margin cycle
    // example value: 0.00000145
    #[serde(rename = "estimate")]
    pub r#estimate: rust_decimal::Decimal,
    
    // hourly borrow rate in the previous spot margin cycle
    // example value: 0.00000144
    #[serde(rename = "previous")]
    pub r#previous: rust_decimal::Decimal,
    }