// 
// Generated by oce-gen
// DO NOT EDIT
// 
use serde::Deserialize;

#[derive(Deserialize, Default)]
#[serde(default)]
pub struct BorrowHistory {
    // no description
    // example value: BTC
    #[serde(rename = "coin")]
    pub r#coin: String,
    
    // amount of coin you paid as interest on the borrow
    // example value: 0.00047864470072
    #[serde(rename = "cost")]
    pub r#cost: rust_decimal::Decimal,
    
    // borrow rate
    // example value: 0.00001961096
    #[serde(rename = "rate")]
    pub r#rate: rust_decimal::Decimal,
    
    // amount borrowed
    // example value: 24.407
    #[serde(rename = "size")]
    pub r#size: rust_decimal::Decimal,
    
    // time of interest payment
    // example value: 2021-04-06T20:00:00+00:00
    #[serde(rename = "time")]
    pub r#time: chrono::DateTime<chrono::Utc>,
    }