// 
// Generated by oce-gen
// DO NOT EDIT
// 
use serde::Deserialize;

#[derive(Deserialize, Default)]
#[serde(default)]
pub struct BorrowSummary {
    // no description
    // example value: BTC
    #[serde(rename = "coin")]
    pub r#coin: String,
    
    // average matched borrowed and lent amount over the last 24h
    // example value: 120.1
    #[serde(rename = "size")]
    pub r#size: rust_decimal::Decimal,
    }