// 
// Generated by oce-gen
// DO NOT EDIT
// 
use serde::Deserialize;

#[derive(Deserialize, Default)]
#[serde(default)]
pub struct History {
    // no description
    // example value: USD
    #[serde(rename = "coin")]
    pub r#coin: String,
    
    // no description
    // example value: 2021-04-06T20:00:00+00:00
    #[serde(rename = "time")]
    pub r#time: chrono::DateTime<chrono::Utc>,
    
    // hourly lending rate for this cycle
    // example value: 0.00002283
    #[serde(rename = "rate")]
    pub r#rate: rust_decimal::Decimal,
    
    // total size matched between borrowers and lenders
    // example value: 615974048.2224404
    #[serde(rename = "size")]
    pub r#size: rust_decimal::Decimal,
    }