// 
// Generated by oce-gen
// DO NOT EDIT
// 
use serde::Deserialize;

#[derive(Deserialize, Default)]
#[serde(default)]
pub struct LendingHistory {
    // no description
    // example value: BTC
    #[serde(rename = "coin")]
    pub r#coin: String,
    
    // amount of coin you were paid as interest on the loan
    // example value: 0.00047864470072
    #[serde(rename = "proceeds")]
    pub r#proceeds: rust_decimal::Decimal,
    
    // lending rate
    // example value: 0.00001961096
    #[serde(rename = "rate")]
    pub r#rate: rust_decimal::Decimal,
    
    // amount lent
    // example value: 24.407
    #[serde(rename = "size")]
    pub r#size: rust_decimal::Decimal,
    
    // time of interest payment
    // example value: 2020-11-30T12:00:00+00:00
    #[serde(rename = "time")]
    pub r#time: chrono::DateTime<chrono::Utc>,
    }