// 
// Generated by oce-gen
// DO NOT EDIT
// 
use serde::Deserialize;

#[derive(Deserialize, Default)]
#[serde(default)]
pub struct LendingInfo {
    // no description
    // example value: USD
    #[serde(rename = "coin")]
    pub r#coin: String,
    
    // additional size you can lend
    // example value: 10026.5
    #[serde(rename = "lendable")]
    pub r#lendable: rust_decimal::Decimal,
    
    // size either in lending offers or not yet unlocked from lending offers
    // example value: 100
    #[serde(rename = "locked")]
    pub r#locked: rust_decimal::Decimal,
    
    // minimum rate at which your offers will lend
    // example value: 0.000001
    #[serde(rename = "minRate")]
    pub r#min_rate: rust_decimal::Decimal,
    
    // size in your lending offers
    // example value: 100
    #[serde(rename = "offered")]
    pub r#offered: rust_decimal::Decimal,
    }