// 
// Generated by oce-gen
// DO NOT EDIT
// 
use serde::Deserialize;

#[derive(Deserialize, Default)]
#[serde(default)]
pub struct MarketInfo {
    // no description
    // example value: BTC
    #[serde(rename = "coin")]
    pub r#coin: String,
    
    // amount of coin currently borrowed
    // example value: 0
    #[serde(rename = "borrowed")]
    pub r#borrowed: rust_decimal::Decimal,
    
    // amount of coin that can be spent buying the other coin in the supplied market, including what's borrowable with margin
    // example value: 3.87278021
    #[serde(rename = "free")]
    pub r#free: rust_decimal::Decimal,
    
    // estimated hourly borrow rate for the next spot margin cycle
    // example value: 0.00000145
    #[serde(rename = "estimatedRate")]
    pub r#estimated_rate: rust_decimal::Decimal,
    
    // hourly borrow rate in the previous spot margin cycle
    // example value: 0.00000144
    #[serde(rename = "previousRate")]
    pub r#previous_rate: rust_decimal::Decimal,
    }