// 
// Generated by oce-gen
// DO NOT EDIT
// 
use serde::Deserialize;
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Deserialize, Debug)]
pub struct Offer {
    // no description
    // example value: BTC
    #[serde(rename = "coin")]
    #[serde_as(deserialize_as = "DefaultOnNull")]
    pub r#coin: String,
    
    // hourly rate at which you will lend, if matched
    // example value: 0.000001
    #[serde(rename = "rate")]
    #[serde_as(deserialize_as = "DefaultOnNull")]
    pub r#rate: rust_decimal::Decimal,
    
    // amount you will lend, if matched
    // example value: 1.9
    #[serde(rename = "size")]
    #[serde_as(deserialize_as = "DefaultOnNull")]
    pub r#size: rust_decimal::Decimal,
    }