[schema]
name = "markets"
values = [
"1INCH-PERP",
"1INCH-0624",
"1INCH-0930",
"1INCH/USD",
"AAPL-0624",
"AAPL-0930",
"AAPL/USD",
"AAVE-PERP",
"AAVE-0624",
"AAVE-0930",
"AAVE/USD",
"AAVE/USDT",
"ABNB-0624",
"ABNB-0930",
"ABNB/USD",
"ACB-0624",
"ACB-0930",
"ACB/USD",
"ADA-PERP",
"ADA-0624",
"ADA-0930",
"AGLD-PERP",
"AGLD/USD",
"AKRO/USD",
"AKRO/USDT",
"ALCX-PERP",
"ALCX/USD",
"ALEPH/USD",
"ALGO-PERP",
"ALGO-0624",
"ALGO-0930",
"ALGO/USD",
"ALGO/USDT",
"ALICE-PERP",
"ALICE/USD",
"ALPHA-PERP",
"ALPHA/USD",
"ALT-PERP",
"ALT-0624",
"ALT-0930",
"AMC-0624",
"AMC-0930",
"AMC/USD",
"AMD-0624",
"AMD-0930",
"AMD/USD",
"AMPL-PERP",
"AMPL/USD",
"AMPL/USDT",
"AMZN-0624",
"AMZN-0930",
"AMZN/USD",
"ANC-PERP",
"ANC/USD",
"APE-PERP",
"APE-0930",
"APE/USD",
"APHA/USD",
"AR-PERP",
"ARKK-0624",
"ARKK-0930",
"ARKK/USD",
"ASD-PERP",
"ASD/USD",
"ATLAS-PERP",
"ATLAS/USD",
"ATOM-PERP",
"ATOM-0624",
"ATOM-0930",
"ATOM/USD",
"ATOM/USDT",
"AUDIO-PERP",
"AUDIO/USD",
"AUDIO/USDT",
"AURY/USD",
"AVAX-PERP",
"AVAX-0624",
"AVAX-0930",
"AVAX/BTC",
"AVAX/USD",
"AVAX/USDT",
"AXS-PERP",
"AXS-0930",
"AXS/USD",
"BABA-0624",
"BABA-0930",
"BABA/USD",
"BADGER-PERP",
"BADGER/USD",
"BAL-PERP",
"BAL-0624",
"BAL-0930",
"BAL/USD",
"BAL/USDT",
"BAND-PERP",
"BAND/USD",
"BAO-PERP",
"BAO/USD",
"BAR/USD",
"BAT-PERP",
"BAT/JPY",
"BAT/USD",
"BB-0624",
"BB-0930",
"BB/USD",
"BCH-PERP",
"BCH-0624",
"BCH-0930",
"BCH/BTC",
"BCH/JPY",
"BCH/USD",
"BCH/USDT",
"BICO/USD",
"BILI-0624",
"BILI-0930",
"BILI/USD",
"BIT-PERP",
"BIT/USD",
"BITO-0624",
"BITO-0930",
"BITO/USD",
"BITW-0624",
"BITW-0930",
"BITW/USD",
"BLT/USD",
"BNB-PERP",
"BNB-0624",
"BNB-0930",
"BNB/BTC",
"BNB/USD",
"BNB/USDT",
"BNT-PERP",
"BNT/USD",
"BNTX-0624",
"BNTX-0930",
"BNTX/USD",
"BOBA-PERP",
"BOBA/USD",
"BOLSONARO2022",
"BRZ-PERP",
"BRZ/USD",
"BRZ/USDT",
"BSV-PERP",
"BSV-0624",
"BSV-0930",
"BTC-PERP",
"BTC-MOVE-0620",
"BTC-MOVE-0621",
"BTC-0624",
"BTC-MOVE-2022Q2",
"BTC-MOVE-WK-0624",
"BTC-MOVE-WK-0701",
"BTC-MOVE-WK-0708",
"BTC-MOVE-WK-0715",
"BTC-0930",
"BTC-MOVE-2022Q3",
"BTC-1230",
"BTC-MOVE-2022Q4",
"BTC/AUD",
"BTC/BRZ",
"BTC/EUR",
"BTC/JPY",
"BTC/TRYB",
"BTC/USD",
"BTC/USDT",
"BTT-PERP",
"BTT/USD",
"BYND-0624",
"BYND-0930",
"BYND/USD",
"C98-PERP",
"C98/USD",
"CAD/USD",
"CAKE-PERP",
"CEL-PERP",
"CEL-0624",
"CEL-0930",
"CEL/BTC",
"CEL/USD",
"CELO-PERP",
"CGC-0624",
"CGC-0930",
"CGC/USD",
"CHR-PERP",
"CHR/USD",
"CHZ-PERP",
"CHZ-0624",
"CHZ-0930",
"CHZ/USD",
"CHZ/USDT",
"CITY/USD",
"CLV-PERP",
"CLV/USD",
"COIN/USD",
"COMP-PERP",
"COMP-0624",
"COMP-0930",
"COMP/USD",
"COMP/USDT",
"CONV-PERP",
"CONV/USD",
"COPE/USD",
"CQT/USD",
"CREAM-PERP",
"CREAM/USD",
"CREAM/USDT",
"CRO-PERP",
"CRO/USD",
"CRON-0624",
"CRON-0930",
"CRON/USD",
"CRV-PERP",
"CRV/USD",
"CTX/USD",
"CTX/USDT",
"CUSDT-PERP",
"CUSDT/USD",
"CUSDT/USDT",
"CVC-PERP",
"CVC/USD",
"CVX-PERP",
"CVX/USD",
"DAI/USD",
"DAI/USDT",
"DASH-PERP",
"DAWN-PERP",
"DAWN/USD",
"DEFI-PERP",
"DEFI-0624",
"DEFI-0930",
"DENT-PERP",
"DENT/USD",
"DFL/USD",
"DKNG-0624",
"DKNG-0930",
"DKNG/USD",
"DMG/USD",
"DMG/USDT",
"DODO-PERP",
"DODO/USD",
"DOGE-PERP",
"DOGE-0624",
"DOGE-0930",
"DOGE/BTC",
"DOGE/USD",
"DOGE/USDT",
"DOT-PERP",
"DOT-0624",
"DOT-0930",
"DOT/BTC",
"DOT/JPY",
"DOT/USD",
"DOT/USDT",
"DRGN-PERP",
"DRGN-0624",
"DYDX-PERP",
"DYDX/USD",
"EDEN-PERP",
"EDEN-0624",
"EDEN/USD",
"EGLD-PERP",
"EMB/USD",
"ENJ-PERP",
"ENJ/USD",
"ENS-PERP",
"ENS/USD",
"EOS-PERP",
"EOS-0624",
"EOS-0930",
"ETC-PERP",
"ETH-PERP",
"ETH-0624",
"ETH-0930",
"ETH-1230",
"ETH/AUD",
"ETH/BRZ",
"ETH/BTC",
"ETH/EUR",
"ETH/JPY",
"ETH/USD",
"ETH/USDT",
"ETHE-0624",
"ETHE-0930",
"ETHE/USD",
"EUR/USD",
"EURT/EUR",
"EURT/USD",
"EURT/USDT",
"EXCH-PERP",
"EXCH-0624",
"EXCH-0930",
"FB-0624",
"FB-0930",
"FB/USD",
"FIDA-PERP",
"FIDA/USD",
"FIDA/USDT",
"FIL-PERP",
"FIL-0624",
"FIL-0930",
"FLM-PERP",
"FLOW-PERP",
"FRONT/USD",
"FRONT/USDT",
"FTM-PERP",
"FTM-0930",
"FTM/USD",
"FTT-PERP",
"FTT/BTC",
"FTT/JPY",
"FTT/USD",
"FTT/USDT",
"FXS-PERP",
"FXS/USD",
"GAL-PERP",
"GAL/USD",
"GALA-PERP",
"GALA/USD",
"GALFAN/USD",
"GARI/USD",
"GBP/USD",
"GBTC-0624",
"GBTC-0930",
"GBTC/USD",
"GDX-0624",
"GDX-0930",
"GDX/USD",
"GDXJ-0624",
"GDXJ-0930",
"GDXJ/USD",
"GENE/USD",
"GLD-0624",
"GLD-0930",
"GLD/USD",
"GLMR-PERP",
"GLXY/USD",
"GME-0624",
"GME-0930",
"GME/USD",
"GMT-PERP",
"GMT-0930",
"GMT/USD",
"GODS/USD",
"GOG/USD",
"GOOGL-0624",
"GOOGL-0930",
"GOOGL/USD",
"GRT-PERP",
"GRT-0624",
"GRT-0930",
"GRT/USD",
"GST-PERP",
"GST-0930",
"GST/USD",
"GST/USDT",
"GT/USD",
"HBAR-PERP",
"HGET/USD",
"HGET/USDT",
"HMT/USD",
"HNT-PERP",
"HNT/USD",
"HNT/USDT",
"HOLY-PERP",
"HOLY/USD",
"HOOD/USD",
"HOT-PERP",
"HT-PERP",
"HT/USD",
"HUM-PERP",
"HUM/USD",
"HXRO/USD",
"HXRO/USDT",
"ICP-PERP",
"ICX-PERP",
"IMX-PERP",
"IMX/USD",
"INDI/USD",
"INTER/USD",
"IOST-PERP",
"IOTA-PERP",
"JASMY-PERP",
"JET/USD",
"JOE/USD",
"JST/USD",
"KAVA-PERP",
"KBTT-PERP",
"KBTT/USD",
"KIN-PERP",
"KIN/USD",
"KNC-PERP",
"KNC/USD",
"KNC/USDT",
"KSHIB-PERP",
"KSHIB/USD",
"KSM-PERP",
"KSOS-PERP",
"KSOS/USD",
"LEO-PERP",
"LEO/USD",
"LINA-PERP",
"LINA/USD",
"LINK-PERP",
"LINK-0624",
"LINK-0930",
"LINK/BTC",
"LINK/USD",
"LINK/USDT",
"LOOKS-PERP",
"LOOKS/USD",
"LRC-PERP",
"LRC/USD",
"LTC-PERP",
"LTC-0624",
"LTC-0930",
"LTC/BTC",
"LTC/JPY",
"LTC/USD",
"LTC/USDT",
"LUA/USD",
"LUA/USDT",
"MANA-PERP",
"MANA/USD",
"MAPS-PERP",
"MAPS/USD",
"MAPS/USDT",
"MATH/USD",
"MATH/USDT",
"MATIC-PERP",
"MATIC/BTC",
"MATIC/USD",
"MBS/USD",
"MCB-PERP",
"MCB/USD",
"MEDIA-PERP",
"MEDIA/USD",
"MER-PERP",
"MER/USD",
"MID-PERP",
"MID-0624",
"MID-0930",
"MINA-PERP",
"MKR-PERP",
"MKR/USD",
"MKR/USDT",
"MNGO-PERP",
"MNGO/USD",
"MOB-PERP",
"MOB/USD",
"MOB/USDT",
"MRNA-0624",
"MRNA-0930",
"MRNA/USD",
"MSOL/USD",
"MSTR-0624",
"MSTR-0930",
"MSTR/USD",
"MTA-PERP",
"MTA/USD",
"MTA/USDT",
"MTL-PERP",
"MTL/USD",
"MVDA10-PERP",
"MVDA25-PERP",
"NEAR-PERP",
"NEAR/USD",
"NEAR/USDT",
"NEO-PERP",
"NEXO/USD",
"NFLX-0624",
"NFLX-0930",
"NFLX/USD",
"NIO-0624",
"NIO-0930",
"NIO/USD",
"NOK-0624",
"NOK-0930",
"NOK/USD",
"NVDA-0624",
"NVDA-0930",
"NVDA/USD",
"OKB-PERP",
"OKB-0624",
"OKB-0930",
"OKB/USD",
"OMG-PERP",
"OMG-0624",
"OMG-0930",
"OMG/USD",
"ONE-PERP",
"ONT-PERP",
"OP-PERP",
"OP-0930",
"ORBS-PERP",
"ORBS/USD",
"OXY-PERP",
"OXY/USD",
"OXY/USDT",
"PAXG-PERP",
"PAXG/USD",
"PAXG/USDT",
"PENN-0624",
"PENN-0930",
"PENN/USD",
"PEOPLE-PERP",
"PEOPLE/USD",
"PERP-PERP",
"PERP/USD",
"PFE-0624",
"PFE-0930",
"PFE/USD",
"POLIS-PERP",
"POLIS/USD",
"PORT/USD",
"TRUMP2024",
"PRISM/USD",
"PRIV-PERP",
"PRIV-0624",
"PRIV-0930",
"PROM-PERP",
"PROM/USD",
"PSG/USD",
"PSY/USD",
"PTU/USD",
"PUNDIX-PERP",
"PUNDIX/USD",
"PYPL-0624",
"PYPL-0930",
"PYPL/USD",
"QI/USD",
"QTUM-PERP",
"RAMP-PERP",
"RAMP/USD",
"RAY-PERP",
"RAY/USD",
"REAL/USD",
"REEF-PERP",
"REEF-0624",
"REEF/USD",
"REN-PERP",
"REN/USD",
"RNDR-PERP",
"RNDR/USD",
"RON-PERP",
"ROOK-PERP",
"ROOK/USD",
"ROOK/USDT",
"ROSE-PERP",
"RSR-PERP",
"RSR/USD",
"RUNE-PERP",
"SAND-PERP",
"SAND/USD",
"SC-PERP",
"SCRT-PERP",
"SECO-PERP",
"SECO/USD",
"SHIB-PERP",
"SHIB/USD",
"SHIT-PERP",
"SHIT-0624",
"SHIT-0930",
"SKL-PERP",
"SKL/USD",
"SLND/USD",
"SLP-PERP",
"SLP/USD",
"SLRS/USD",
"SLV-0624",
"SLV-0930",
"SLV/USD",
"SNX-PERP",
"SNX/USD",
"SNY/USD",
"SOL-PERP",
"SOL-0624",
"SOL-0930",
"SOL/BTC",
"SOL/JPY",
"SOL/USD",
"SOL/USDT",
"SOS-PERP",
"SOS/USD",
"SPA/USD",
"SPELL-PERP",
"SPELL/USD",
"SPY-0624",
"SPY-0930",
"SPY/USD",
"SQ-0624",
"SQ-0930",
"SQ/USD",
"SRM-PERP",
"SRM/USD",
"SRM/USDT",
"SRN-PERP",
"STARS/USD",
"STEP-PERP",
"STEP/USD",
"STETH/USD",
"STG/USD",
"STMX-PERP",
"STMX/USD",
"STORJ-PERP",
"STORJ/USD",
"STSOL/USD",
"STX-PERP",
"SUN/USD",
"SUSHI-PERP",
"SUSHI-0624",
"SUSHI-0930",
"SUSHI/BTC",
"SUSHI/USD",
"SUSHI/USDT",
"SXP-PERP",
"SXP-0624",
"SXP-0930",
"SXP/BTC",
"SXP/USD",
"SXP/USDT",
"THETA-PERP",
"THETA-0624",
"TLM-PERP",
"TLM/USD",
"TLRY-0624",
"TLRY-0930",
"TLRY/USD",
"TOMO-PERP",
"TOMO/USD",
"TOMO/USDT",
"TONCOIN-PERP",
"TONCOIN/USD",
"TRU-PERP",
"TRU/USD",
"TRU/USDT",
"TRX-PERP",
"TRX-0624",
"TRX-0930",
"TRX/BTC",
"TRX/USD",
"TRX/USDT",
"TRYB-PERP",
"TRYB/USD",
"TSLA-0624",
"TSLA-0930",
"TSLA/BTC",
"TSLA/DOGE",
"TSLA/USD",
"TSM-0624",
"TSM-0930",
"TSM/USD",
"TULIP-PERP",
"TULIP/USD",
"TWTR-0624",
"TWTR-0930",
"TWTR/USD",
"UBER-0624",
"UBER-0930",
"UBER/USD",
"UBXT/USD",
"UBXT/USDT",
"UMEE/USD",
"UNI-PERP",
"UNI-0624",
"UNI-0930",
"UNI/BTC",
"UNI/USD",
"UNI/USDT",
"UNISWAP-PERP",
"UNISWAP-0624",
"UNISWAP-0930",
"USD/JPY",
"USDT-PERP",
"USDT-0624",
"USDT-0930",
"USDT/USD",
"USO-0624",
"USO-0930",
"USO/USD",
"VET-PERP",
"VGX/USD",
"WAVES-PERP",
"WAVES-0624",
"WAVES-0930",
"WAVES/USD",
"WBTC/BTC",
"WBTC/USD",
"WFLOW/USD",
"WNDR/USD",
"WRX/USD",
"WRX/USDT",
"WSB-0624",
"WSB-0930",
"XAUT-PERP",
"XAUT-0624",
"XAUT/USD",
"XAUT/USDT",
"XEM-PERP",
"XLM-PERP",
"XMR-PERP",
"XRP-PERP",
"XRP-0624",
"XRP-0930",
"XRP/BTC",
"XRP/JPY",
"XRP/USD",
"XRP/USDT",
"XTZ-PERP",
"XTZ-0624",
"XTZ-0930",
"YFI-PERP",
"YFI-0624",
"YFI-0930",
"YFI/BTC",
"YFI/USD",
"YFI/USDT",
"YFII-PERP",
"YFII/USD",
"YGG/USD",
"ZEC-PERP",
"ZIL-PERP",
"ZM-0624",
"ZM-0930",
"ZM/USD",
"ZRX-PERP",
"ZRX/USD",
"ADABEAR/USD",
"ADABULL/USD",
"ADAHALF/USD",
"ADAHEDGE/USD",
"ALGOBEAR/USD",
"ALGOBULL/USD",
"ALGOHALF/USD",
"ALGOHEDGE/USD",
"ALTBEAR/USD",
"ALTBULL/USD",
"ALTHALF/USD",
"ALTHEDGE/USD",
"ASDBEAR/USD",
"ASDBEAR/USDT",
"ASDBULL/USD",
"ASDBULL/USDT",
"ASDHALF/USD",
"ASDHEDGE/USD",
"ATOMBEAR/USD",
"ATOMBULL/USD",
"ATOMHALF/USD",
"ATOMHEDGE/USD",
"BALBEAR/USD",
"BALBEAR/USDT",
"BALBULL/USD",
"BALBULL/USDT",
"BALHALF/USD",
"BALHEDGE/USD",
"BCHBEAR/USD",
"BCHBEAR/USDT",
"BCHBULL/USD",
"BCHBULL/USDT",
"BCHHALF/USD",
"BCHHEDGE/USD",
"BEAR/USD",
"BEAR/USDT",
"BEARSHIT/USD",
"BNBBEAR/USD",
"BNBBEAR/USDT",
"BNBBULL/USD",
"BNBBULL/USDT",
"BNBHALF/USD",
"BNBHEDGE/USD",
"BSVBEAR/USD",
"BSVBEAR/USDT",
"BSVBULL/USD",
"BSVBULL/USDT",
"BSVHALF/USD",
"BSVHEDGE/USD",
"BULL/USD",
"BULL/USDT",
"BULLSHIT/USD",
"BVOL/USD",
"COMPBEAR/USD",
"COMPBEAR/USDT",
"COMPBULL/USD",
"COMPBULL/USDT",
"COMPHALF/USD",
"COMPHEDGE/USD",
"CUSDTBEAR/USD",
"CUSDTBEAR/USDT",
"CUSDTBULL/USD",
"CUSDTBULL/USDT",
"CUSDTHALF/USD",
"CUSDTHEDGE/USD",
"DEFIBEAR/USD",
"DEFIBEAR/USDT",
"DEFIBULL/USD",
"DEFIBULL/USDT",
"DEFIHALF/USD",
"DEFIHEDGE/USD",
"DOGEBEAR2021/USD",
"DOGEBULL/USD",
"DOGEHALF/USD",
"DOGEHEDGE/USD",
"DRGNBEAR/USD",
"DRGNBULL/USD",
"DRGNHALF/USD",
"DRGNHEDGE/USD",
"EOSBEAR/USD",
"EOSBEAR/USDT",
"EOSBULL/USD",
"EOSBULL/USDT",
"EOSHALF/USD",
"EOSHEDGE/USD",
"ETCBEAR/USD",
"ETCBULL/USD",
"ETCHALF/USD",
"ETCHEDGE/USD",
"ETHBEAR/USD",
"ETHBEAR/USDT",
"ETHBULL/USD",
"ETHBULL/USDT",
"ETHHALF/USD",
"ETHHEDGE/USD",
"EXCHBEAR/USD",
"EXCHBULL/USD",
"EXCHHALF/USD",
"EXCHHEDGE/USD",
"GRTBEAR/USD",
"GRTBULL/USD",
"HALF/USD",
"HALFSHIT/USD",
"HEDGE/USD",
"HEDGESHIT/USD",
"HTBEAR/USD",
"HTBULL/USD",
"HTHALF/USD",
"HTHEDGE/USD",
"IBVOL/USD",
"KNCBEAR/USD",
"KNCBEAR/USDT",
"KNCBULL/USD",
"KNCBULL/USDT",
"KNCHALF/USD",
"KNCHEDGE/USD",
"LEOBEAR/USD",
"LEOBULL/USD",
"LEOHALF/USD",
"LEOHEDGE/USD",
"LINKBEAR/USD",
"LINKBEAR/USDT",
"LINKBULL/USD",
"LINKBULL/USDT",
"LINKHALF/USD",
"LINKHEDGE/USD",
"LTCBEAR/USD",
"LTCBEAR/USDT",
"LTCBULL/USD",
"LTCBULL/USDT",
"LTCHALF/USD",
"LTCHEDGE/USD",
"MATICBEAR2021/USD",
"MATICBULL/USD",
"MATICHALF/USD",
"MATICHEDGE/USD",
"MIDBEAR/USD",
"MIDBULL/USD",
"MIDHALF/USD",
"MIDHEDGE/USD",
"MKRBEAR/USD",
"MKRBULL/USD",
"OKBBEAR/USD",
"OKBBULL/USD",
"OKBHALF/USD",
"OKBHEDGE/USD",
"PAXGBEAR/USD",
"PAXGBULL/USD",
"PAXGHALF/USD",
"PAXGHEDGE/USD",
"PRIVBEAR/USD",
"PRIVBULL/USD",
"PRIVHALF/USD",
"PRIVHEDGE/USD",
"SUSHIBEAR/USD",
"SUSHIBULL/USD",
"SXPBEAR/USD",
"SXPBULL/USD",
"SXPHALF/USD",
"SXPHALF/USDT",
"SXPHEDGE/USD",
"THETABEAR/USD",
"THETABULL/USD",
"THETAHALF/USD",
"THETAHEDGE/USD",
"TOMOBEAR2021/USD",
"TOMOBULL/USD",
"TOMOHALF/USD",
"TOMOHEDGE/USD",
"TRXBEAR/USD",
"TRXBULL/USD",
"TRXHALF/USD",
"TRXHEDGE/USD",
"TRYBBEAR/USD",
"TRYBBULL/USD",
"TRYBHALF/USD",
"TRYBHEDGE/USD",
"UNISWAPBEAR/USD",
"UNISWAPBULL/USD",
"USDTBEAR/USD",
"USDTBULL/USD",
"USDTHALF/USD",
"USDTHEDGE/USD",
"VETBEAR/USD",
"VETBEAR/USDT",
"VETBULL/USD",
"VETBULL/USDT",
"VETHEDGE/USD",
"XAUTBEAR/USD",
"XAUTBULL/USD",
"XAUTHALF/USD",
"XAUTHEDGE/USD",
"XLMBEAR/USD",
"XLMBULL/USD",
"XRPBEAR/USD",
"XRPBEAR/USDT",
"XRPBULL/USD",
"XRPBULL/USDT",
"XRPHALF/USD",
"XRPHEDGE/USD",
"XTZBEAR/USD",
"XTZBEAR/USDT",
"XTZBULL/USD",
"XTZBULL/USDT",
"XTZHALF/USD",
"XTZHEDGE/USD",
"ZECBEAR/USD",
"ZECBULL/USD",
]
