[schema]
name = "trade"
fields = [
{ name = "id", value = 3855995, type = "uint64", description = "trade id" },
{ name = "liquidation", value = false, description = "if this trade involved a liquidation order" },
{ name = "price", value = 3857.75 },
{ name = "side", value = "buy" },
{ name = "size", value = 0.111 },
{ name = "time", value = "2019-03-20T18:16:23.397991+00:00" },
]
