// 
// Generated by oce-gen
// DO NOT EDIT
// 
use serde::Deserialize;
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Deserialize, Debug)]
pub struct Candle {
    // start time of the window
    // example value: 2019-06-24T17:15:00+00:00
    #[serde(rename = "startTime")]
    #[serde_as(deserialize_as = "DefaultOnNull")]
    pub r#start_time: String,
    
    // mark price at startTime
    // example value: 11059.25
    #[serde(rename = "open")]
    #[serde_as(deserialize_as = "DefaultOnNull")]
    pub r#open: rust_decimal::Decimal,
    
    // mark price at the end of the window: startTime + resolution
    // example value: 11055.25
    #[serde(rename = "close")]
    #[serde_as(deserialize_as = "DefaultOnNull")]
    pub r#close: rust_decimal::Decimal,
    
    // highest mark price over the window
    // example value: 11089
    #[serde(rename = "high")]
    #[serde_as(deserialize_as = "DefaultOnNull")]
    pub r#high: rust_decimal::Decimal,
    
    // lowest mark price over the window
    // example value: 11059.25
    #[serde(rename = "low")]
    #[serde_as(deserialize_as = "DefaultOnNull")]
    pub r#low: rust_decimal::Decimal,
    
    // volume traded in the window
    // example value: 464193.95725
    #[serde(rename = "volume")]
    #[serde_as(deserialize_as = "DefaultOnNull")]
    pub r#volume: rust_decimal::Decimal,
    }