//
// Generated by oce-gen
// DO NOT EDIT
//
use serde::Deserialize;

#[derive(Deserialize, Default)]
#[serde(default)]
pub struct Candle {
    // start time of the window
    // example value: 2019-06-24T17:15:00+00:00
    #[serde(rename = "startTime")]
    pub r#start_time: String,

    // mark price at startTime
    // example value: 11059.25
    #[serde(rename = "open")]
    pub r#open: rust_decimal::Decimal,

    // mark price at the end of the window: startTime + resolution
    // example value: 11055.25
    #[serde(rename = "close")]
    pub r#close: rust_decimal::Decimal,

    // highest mark price over the window
    // example value: 11089
    #[serde(rename = "high")]
    pub r#high: rust_decimal::Decimal,

    // lowest mark price over the window
    // example value: 11059.25
    #[serde(rename = "low")]
    pub r#low: rust_decimal::Decimal,

    // volume traded in the window
    // example value: 464193.95725
    #[serde(rename = "volume")]
    pub r#volume: rust_decimal::Decimal,
}
