// 
// Generated by oce-gen
// DO NOT EDIT
// 
// This section covers all types of markets on FTX: spot, perpetual futures, expiring futures, and MOVE contracts. Examples for each type are BTC/USD, BTC-PERP, BTC-0626, and BTC-MOVE-1005. For futures that expired in 2019, prepend a 2019 to the date, like so: BTC-20190628 or BTC-MOVE-20190923.

pub mod candle;
pub mod market;
pub mod orderbook;
pub mod trade;
