// 
// Generated by oce-gen
// DO NOT EDIT
// 
use serde::Deserialize;

#[derive(Deserialize, Default)]
#[serde(default)]
pub struct Orderbook {
    // Array with price and size
    // example value: [[4114.25,6.263]]
    #[serde(rename = "asks")]
    pub r#asks: Vec<Vec<rust_decimal::Decimal>>,
    
    // Array with price and size
    // example value: [[4112,49.29]]
    #[serde(rename = "bids")]
    pub r#bids: Vec<Vec<rust_decimal::Decimal>>,
    }